# Configure database credentials and connection pool.
database:
  # JDBC URL (MySQL recommended)
  url: jdbc:mysql://127.0.0.1:3306/admintools

  # Database username
  user: root

  # Database password
  pass:

  # Connections in the pool.
  threads: 1

# List of commands that are unable for use when a player is muted
mute-commands: []
